### ISSUE TITLE
Refresh button not updating the list

### ISSUE THREAD

**Issue by addison74** [sreichel/magento-Defcon2-Imaclean#4]
ImaClean is doing a great job only for the first Refresh.

1) ImaClean found an orphan image named image1.jpg. 

2) I went to phpMyAdmin and corrected image name pointing correctly to image1.jpg. Now the file is on disk and also in database.

3) I pushed [Refresh] button and the image is still there like an orphan. This was not good, because if someone is deleting this file, because it is in DB and associated with a product will create trouble.

As a temporary method in this case I truncated imaclean table, incremented it from 1, then clicking on [Refresh] button that image was not longer listed. ImaClean version is the latest version download from here today.

We need a fix for this.

**Comment by addison74** [comment]
Another scenario. Create an image in your /media/product/catalog for being identified by ImaClean. Assure you have imaclean table empty and auto_incremented from 1. Click on [Refresh] button and the image will appear in the list. Go to your file system and delete manually this file. Go and Refresh once again. Image is still there.

Conclusion when you click on Refresh you should delete all records in imaclean database, reset the table auto_increment to 1, then find which files are not in database but on the file system. Refresh means starting from scratch, if any changes in database or file system occur ImaClean will be able to identify them.

**Comment by sreichel** [comment]
FYI, i'm not the author of this extension. I've just hosted it to install it via modman/composer.

However, thank's for reporting this. As soon  i have time, i'll try to fix it. PR are welcome ;)

**Comment by addison74** [comment]
I just checked your latest version and it seems you fixed this issue. When I press the [Refresh] button the imaclean table is truncated then auto_incremented to 1. 

```/app/code/community/Defcon2/Imaclean/Helper/Data.php```

```
public function compareList()
    {
        $model = Mage::getModel('defcon2imaclean/imaclean');

        $resource = $model->getResource();
        $connection = $resource->getReadConnection();
        $connection->truncateTable($resource->getMainTable());
        $connection->changeTableAutoIncrement($resource->getMainTable(), 1);
```
