### ISSUE TITLE
app/design/adminhtml/default/default/layout/defcon2imaclean.xml

### ISSUE THREAD

**Issue by szepeviktor** [sreichel/magento-Defcon2-Imaclean#7]
@sreichel Good morning!

In v1.2.1 package.xml for Magento 1 you declare that `app/design/adminhtml/default/default/layout/defcon2imaclean.xml` is a necessary file. `n98-magerun extension:validate` warns me: Path: FILE NOT FOUND.

Could you describe this file's usage.
Thank you.

**Comment by sreichel** [comment]
Please check extension version. `package.xml` has been removed before v1.1.0 and there is also no `defcon2imaclean.xml`.

**Comment by szepeviktor** [comment]
Thank you.

> package.xml has been removed before v1.1.0 

So you don't plan to release this extension as a package on the marketplace?

**Comment by sreichel** [comment]
Its not my extension. Just download it from Magento Connect hosted here.

**Comment by szepeviktor** [comment]
Really!
https://github.com/sreichel/magento-Defcon2-Imaclean/blob/master/app/code/community/Defcon2/Imaclean/Block/Imaclean.php#L8
