### ISSUE TITLE
Missing images from the admin panel

### ISSUE THREAD

**Issue by gibisk** [sreichel/magento-Defcon2-Imaclean#9]
Hi!
Recently I noticed that after using ImaClean I lost all pictures in the product cards in back-end. In the front-end everything is OK, in the media/catalog/product physically all necessary images are in their places. But when you go to the admin panel to «Images» tab, everything looks as if the product has no images.

For import I use Magmi. If you physically delete any test image from the catalog and then make the import, test image appears in the catalog and in front-end, but not in the item card in back-end.
Has anyone encountered a similar glitch?

I have 2 installations, - same story with both: one installation on 1.7.0.1, another on 1.9.0.1

Theoretically, it is possible to live - making imports if necessary. But it's embarrassing, damn it!

**Comment by addison74** [comment]
Enable Flash in your browser and reload the product editing page. Starting with Magento 1.9.3 Flash uploader was replaced and this issue is gone. In conclusion it is not related to ImaClean extension.

**Comment by sreichel** [comment]
Thanks @ADDISON74
